from typing import List, Any

mcq_questions = [
    "What is the main concern of message authentication? ",
    "Which of the following is NOT a function of message authentication? ",
    "Which alternative function is used for protecting the integrity of a message? ",
    "What is the purpose of a digital signature in message authentication? ",
    "Which method ensures non-repudiation of the message origin? ",
    "What additional measure of authentication does symmetric message encryption provide? ",
    "If symmetric encryption is used, what does the receiver know about the sender's involvement? ",
    "Why does symmetric encryption ensure that the content cannot be altered? ",
    "What confidence does public-key encryption provide regarding the sender? ",
    "Why might recognizing corrupted messages be necessary when using public-key encryption? ",
    "How can both secrecy and authentication be achieved in public-key encryption?",
    "What is the cost associated with achieving both secrecy and authentication in public-key encryption? ",
    "What is a common drawback associated with encryption software? ",
    "Why are encryption hardware costs considered nonnegligible?",
    "What type of data sizes is encryption hardware typically optimized toward? ",
    "In what way might an encryption algorithm be protected? ",
    "What is the main motivation for developing a MAC derived from a cryptographic hash code? ",
    "Why can't a hash function like SHA-1 be used directly as a MAC? ",
    "Which approach, incorporating a secret key into an existing hash algorithm, has received the most support? ",
    "Why are the first two design objectives important for HMAC? ",
    "What is the main advantage of HMAC over other proposed hash-based schemes? ",
    "What does HMAC treat the hash function as? ",
    "How can HMAC retain security if the security of the embedded hash function is compromised? ",
    "What is the significance of the last design objective listed for HMAC? ",
    "Which property of a hash function allows it to be applied to any sized message?",
    "What is the typical relationship between the output size (h) and the size of the input data (M) in a hash function?   ",
    "What property ensures that, given the hash value (h), it is infeasible to find a message (x) such that H(x) equals h?  ",
    "What type of resistance involves the infeasibility of finding any pair of inputs x' ≠ x such that H(x') equals H(x)?   ",
    "What is the main limitation preventing the design of a hash function with no collisions?   ",
    "What is the purpose of using cryptographic hashes in the scenario where Mozilla publishes a new version of Firefox?  ",
    "In the scenario where Alice and Bob want to communicate over an insecure channel, what threat model undermines the integrity provided by cryptographic hashes?   ",
    "What is the main issue with unkeyed hash functions in the context of message integrity?   ",
    "What cryptographic technique involves creating a message digest using a secret symmetric key?   ",
    "What is the term for a message digest that is encrypted using the private key of an asymmetric key pair to form a digital signature?   ",
    "What is the fundamental principle underlying all hash functions in processing input data?   ",
    "How does the XOR operation in the hash function contribute to data integrity?   ",
    "What is the effectiveness of the XOR-based hash function for random data?   ",
    "How does the effectiveness of the XOR-based hash function change with predictably formatted data?  ",
    "What is the purpose of performing a 1-bit circular shift on the hash value in the hash function?   ",
    "What are the steps involved in the procedure to improve the XOR-based hash function?   ",
    "Why is the rotated XOR (RXOR) hash function considered virtually useless for data security in certain scenarios?   ",
    "What does encrypting the entire message plus hash code using the cipher block chaining (CBC) mode involve in the proposed scheme?  ",
    "How can the ciphertext of the message be manipulated in a way that is not detectable by the hash code in the proposed scheme?",
    "What is the primary purpose of a digital signature? ",
    "Which key is used to create a digital signature? ",
    "What does a digital signature ensure regarding the message it signs? ",
    "To verify a digital signature, which key is used? ",
    "What is the term for the process of applying a hash function to the message before creating a digital signature? ",
    "What security property does a digital signature provide to prevent the sender from denying sending the message?",
    "Which cryptographic algorithm is commonly used for creating digital signatures? ",
    "What is the primary purpose of a digital signature, according to NIST FIPS PUB 186-4? ",
    "Which of the following is not one of the specified digital signature algorithms in FIPS 186-4? ",
    "In the digital signature generation process, what does Bob use to create a short block functioning as a digital signature? ",
    "When Alice receives a message with a signature from Bob, what does she use to verify the signature? ",
    "What aspect of confidentiality does the RSA Digital Signature Algorithm NOT provide? ",
    "In the RSA Digital Signature Algorithm, what is the purpose of the RSA Probabilistic Signature Scheme (RSA-PSS)? ",
    "What role does the salt play in the RSA-PSS signature generation process? ",
    "Why does using RSA-PSS result in different signatures for the same message signed twice? ",
    "According to FIPS PUB 186-4, what are the essential elements of a digital signature process? ",
    "What assurance does Alice have when the digital signature verification algorithm returns 'valid'? ",

]

mcq_choices = [
    [
        "Protecting the confidentiality of a message",
        "Ensuring the availability of a message",
        "Protecting the integrity of a message",
        "Validating the identity of the recipient",
    ],
    [
        "Protecting the integrity of a message",
        "Validating the identity of the originator",
        "Ensuring non-repudiation of the origin",
        "Encrypting the message symmetrically",
    ],
    [
        "Message encryption - symmetric",
        "Message authentication code (MAC)",
        "Digital signature",
        "All of the above",
    ],
    [
        "Encrypting the message symmetrically",
        "Verifying the identity of the originator",
        "Ensuring non-repudiation of the origin",
        "Protecting the availability of the message",
    ],
    [
        "Message encryption - symmetric",
        "Message authentication code (MAC)",
        "Digital signature",
        "All of the above",
    ],
    [
        "Sender's identity verification",
        "Receiver's identity verification",
        "Message integrity assurance",
        "Public key disclosure"
    ],
    [
        "Sender must have created it",
        "Receiver must have created it",
        "Message was created by a third party",
        "Sender's identity is anonymous"
    ],
    [
        "Because of the public key",
        "Due to the symmetric key",
        "Sender and receiver share a common key",
        "Message alteration is not prevented by symmetric encryption"
    ],
    [
        "High confidence",
        "Moderate confidence",
        "No confidence",
        "Confidence is irrelevant in public-key encryption"
    ],
    [
        "Public-key exposure",
        "Potential sender anonymity",
        "Message corruption is inherent to public-key encryption",
        "To prevent message alteration"
    ],
    [
        "Encrypting with the sender's public key",
        "Encrypting with the recipient's public key",
        "Signing with the sender's private key and encrypting with the recipient's public key",
        "Signing with the recipient's private key and encrypting with the sender's public key"
    ],
    [
        "No cost",
        "One public-key use",
        "Two public-key uses",
        "Cost is not associated with public-key encryption"
    ],
    [
        "High cost",
        "Low efficiency",
        "Fast performance",
        "Limited availability"
    ],
    [
        "Hardware is inherently expensive",
        "Encryption hardware is slow",
        "Optimization requires additional costs",
        "Nonnegligible costs are not associated with encryption hardware"
    ],
    [
        "Small data sizes",
        "Medium-sized data",
        "Large data sizes",
        "Optimization is independent of data size"
    ],
    [
        "By trade secrets",
        "Through open-source licensing",
        "By encryption standards",
        "By a patent"
    ],
    [
        "Faster execution in hardware",
        "Faster execution in software",
        "Compatibility with DES",
        "Availability of library code"
    ],
    [
        "It is too slow for MAC purposes",
        "It relies on a public key",
        "It lacks a secret key",
        "It performs poorly in software"
    ],
    [
        "RSA",
        "AES",
        "HMAC",
        "MD5"
    ],
    [
        "To make it difficult to replace the hash function",
        "To use the hash function as a black box",
        "To require modifications to the hash function",
        "To make it harder to analyze the strength of HMAC"
    ],
    [
        "It can be proven secure with reasonable cryptographic strengths of the embedded hash function",
        "It performs better in hardware",
        "It relies on a public key",
        "It has a higher execution speed in software"
    ],
    [
        "A complex mathematical equation",
        "A black box",
        "A public key",
        "A secret key"
    ],
    [
        "By using multiple hash functions simultaneously",
        "By replacing the embedded hash function with a more secure one",
        "By changing the secret key",
        "By encrypting the hash function"
    ],
    [
        "It is not relevant to the security of HMAC",
        "It is the only design objective for HMAC",
        "It is the least important design objective",
        "It is the main advantage of HMAC"
    ],
    ["One-way property", "Length extension attack", "Collision resistance", "Weak hash function"],
    ["h is always greater than M", "h is always equal to M", "h is fixed-size", "h is variable size"],
    ["Preimage resistance", "Weak collision resistance", "Second pre-image resistance", "Length extension resistance"],
    ["Weak collision resistance", "Preimage resistance", "Second pre-image resistance", "Length extension resistance"],
    ["Hash functions are inherently flawed", "Pigeonhole principle", "Limited computational power",
     "Design constraints"],
    ["Ensuring data confidentiality", "Preventing length extension attacks",
     "Verifying the integrity of the downloaded program", "Creating digital signatures"],
    ["David modifying the message and the hash", "David modifying only the message", "Communication of the hash value",
     "Bob computing a hash on the message"],
    ["Unpredictability", "Use of secret keys", "Ease of computation", "Unkeyed nature"],
    ["Message Digest Authentication", "Public Key Infrastructure", "Message Authentication Code",
     "Digital Certificate"],
    ["Encrypted Digest", "Secure Hash Algorithm", "Digital Envelope", "Digital Signature"],
    ["Sequential processing", "Block-based processing", "Iterative processing", "Parallel processing"],
    ["It produces a simple parity for each bit position.", "It randomizes the input more completely.",
     "It increases the size of the hash code.", "It guarantees a collision-free hash code."],
    ["2^n", "2-n", "n/2", "n^2"],
    ["It remains the same.", "It decreases.", "It increases.", "It becomes unpredictable."],
    ["To achieve higher data integrity.", "To overcome regularities in the input.", "To simplify the hash computation.",
     "To decrease the size of the hash code."],
    ["Set the hash value to zero and rotate left by one bit.",
     "Rotate left by one bit and XOR the block into the hash value.",
     "XOR the block into the hash value and rotate right by one bit.",
     "Set the hash value to zero and XOR the block into the hash value."],
    ["It is easily reversible and vulnerable to attacks.", "It is computationally expensive.",
     "It produces a hash code with low entropy.", "It can be easily encrypted and decrypted."],
    ["Appending the hash code as the final block.", "Permuting the ciphertext blocks.",
     "Hashing each block separately.", "Using a different encryption mode for the hash code."],
    ["By changing the initialization vector (IV).", "By permuting the message blocks.",
     "By applying a circular shift to the ciphertext.", "By using a different encryption key."],
    ["Encryption", " Data compression", " Authentication", "File storage"],
    ["Sender's public key", "Sender's private key", "Receiver's public key", "Receiver's private key"],
    ["Confidentiality", "Availability", "Integrity", "Non-repudiation"],
    ["Sender's public key", "Sender's private key", "Receiver's public key", "Receiver's private key"],
    ["Encryption", "Decryption", "Hashing", "Compression"],
    ["Confidentiality", "Availability", "Authenticity", "Non-repudiation"],
    ["AES", "RSA", "MD5", "DES"],
    ["Providing confidentiality", "Ensuring data integrity and authenticity", "Preventing data alteration",
     "Encrypting messages"],
    ["Digital Signature Algorithm (DSA)", "Rivest-Shamir-Adleman (RSA) Digital Signature Algorithm",
     "Advanced Encryption Standard (AES)", "Elliptic Curve Digital Signature Algorithm (ECDSA)"],
    ["Alice's public key", "Secure hash function and his private key", "Elliptic curve parameters",
     "Message encryption key"],
    ["Bob's private key", "Digital Signature Algorithm (DSA)", "Bob's public key and a hash value of the message",
     "Elliptic Curve Digital Signature Algorithm (ECDSA)"],
    ["Protection from eavesdropping", "Protection against alteration", "Encryption of the entire message",
     "Use of sender's public key"],
    ["To simplify the algorithm", "To enhance the security of the hash value",
     "To reduce the size of the digital signature", "To improve public key distribution"],
    ["It is used to encrypt the message", "It is added to the hash value to enhance security",
     "It represents the signer's public key", "It serves as the private key in the encryption process"],
    ["It uses a different hash function each time", "It introduces a pseudorandom salt that changes with every use",
     "It encrypts the message differently for each signature", "It applies a different public key for each signature"],
    ["Encryption, decryption, and authentication", "Data integrity, confidentiality, and non-repudiation",
     "Hashing, public key, and private key",
     "Signature generation, signature verification, and cryptographic hash function"],
    ["The message is confidential", "The message has not been altered and is from the alleged signer",
     "The message can be decrypted using the sender's public key", "The message is encrypted with Bob's private key"]]

mcq_correct_answers = [
    "Protecting the integrity of a message",
    "Protecting the confidentiality of a message",
    "All of the above",
    "Ensuring non-repudiation of the origin",
    "Digital signature",
    "Message integrity assurance",
    "Sender must have created it",
    "Sender and receiver share a common key",
    "No confidence",
    "To prevent message alteration",
    "Signing with the sender's private key and encrypting with the recipient's public key",
    "Two public-key uses",
    "Low efficiency",
    "Optimization requires additional costs",
    "Large data sizes",
    "By a patent",
    "Availability of library code",
    "It lacks a secret key",
    "HMAC",
    "To make it difficult to replace the hash function",
    "It can be proven secure with reasonable cryptographic strengths of the embedded hash function",
    "A black box",
    "By replacing the embedded hash function with a more secure one",
    "It is the main advantage of HMAC",
    "One-way property",
    "h is fixed-size",
    "Preimage resistance",
    "Weak collision resistance",
    "Design constraints",
    "Verifying the integrity of the downloaded program",
    "David modifying the message and the hash",
    "Unkeyed nature",
    "Message Authentication Code",
    "Digital Signature",
    "Block-based processing",
    "It randomizes the input more completely.",
    "2-n",
    "It becomes unpredictable.",
    "To overcome regularities in the input.",
    "Rotate left by one bit and XOR the block into the hash value.",
    "It is easily reversible and vulnerable to attacks.",
    "Appending the hash code as the final block.",
    "By permuting the message blocks.",
    "Authentication",
    "Sender's private key",
    "Integrity",
    "Sender's public key",
    "Hashing",
    "Non-repudiation",
    "RSA",
    "Ensuring data integrity and authenticity",
    "Advanced Encryption Standard (AES)",
    "Secure hash function and his private key",
    "Bob's public key and a hash value of the message",
    "Protection from eavesdropping",
    "To enhance the security of the hash value",
    "It is added to the hash value to enhance security",
    "It introduces a pseudorandom salt that changes with every use",
    "Signature generation, signature verification, and cryptographic hash function",
    "The message has not been altered and is from the alleged signer"]

mcq_sources = ["Lecture Slide: 15 Page:3", "Lecture Slide: 15 Page:3", "Lecture Slide: 15 Page:3",
               "Lecture Slide: 15 Page:3", "Lecture Slide: 15 Page:4", "Lecture Slide: 15 Page:4",
               "Lecture Slide: 15 Page:4",
               "Lecture Slide: 15 Page:6", "Lecture Slide: 15 Page:6", "Lecture Slide: 15 Page:6",
               "Lecture Slide: 15 Page:6", "Lecture Slide: 15 Page:7", "Lecture Slide: 15 Page:7",
               "Lecture Slide: 15 Page:7",
               " Lecture Slide: 15 Page:8",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:91",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:93",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:92",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:91",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:91",
               " Network Security Essentials Applications and Standards Sixth edition William Stallings Page:93",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:91",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:93",
               "Lecture Slide: 16, Page: 5", "Lecture Slide: 16, Page: 5", " Lecture Slide: 16, Page: 5",
               "Lecture Slide: 16, Page: 5", "Lecture Slide: 16, Page: 6", " Lecture Slide: 17, Page: 3",
               "Lecture Slide: 17, Page: 4",
               "Lecture Slide: 17, Page: 6", "Lecture Slide: 17, Page: 7", "Lecture Slide: 17, Page: 7",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 87",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 87",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 88",
               " Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 88",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 88",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 87",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 89",
               " Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 88",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 88",
               "Lecture slide: 20, page:7", "Lecture slide: 20, page: 7", "Lecture slide: 20, page: 7",
               "Lecture slide: 20, page: 7",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
               " Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 109",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 109",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 109",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 109",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 109",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111"]

# True or False:
true_false_questions = [
    "Message authentication is concerned with protecting the confidentiality of a message.",
    "Symmetric message encryption alone provides authentication because only the sender and receiver know the key. ",
    "Public-key encryption, by itself, provides confidence in the sender's identity. ",
    "If symmetric encryption is used, the receiver cannot verify that the content has not been altered. ",
    "Using public-key encryption, the sender signs the message with their private key and then encrypts it with the recipient's public key. ",
    "Encryption software is typically faster than encryption hardware.",
    "Encryption hardware costs are usually negligible. ",
    "Encryption hardware is optimized for small data sizes. ",
    "An encryption algorithm cannot be protected by a patent.",
    "Cryptographic hash functions generally execute faster in hardware than conventional encryption algorithms. ",
    "A hash function like SHA-1 can be used directly for Message Authentication Code (MAC) purposes. ",
    "HMAC treats the hash function as a 'black box.",
    "The first design objective of HMAC is to have a complicated replaceability process for the embedded hash function. ",
    "If a faster hash function is desired in an HMAC implementation, the entire HMAC code needs to be modified. ",
    "HMAC cannot retain security if the security of the embedded hash function is compromised. ",
    "The last design objective for HMAC is considered its main advantage over other hash-based schemes. ",
    "HMAC's security is independent of the cryptographic strengths of the embedded hash function. ",
    "A hash function always produces an output of fixed size.   ",
    "A length extension attack allows an attacker to create H(x || m) for any m of their choosing.  ",
    "SHA-1 is currently considered secure.   ",
    "In the context of a length extension attack, SHA-3 is vulnerable.   ",
    "Cryptographic hashes provide integrity when the attacker cannot modify the hash value.   ",
    "Hashes are unkeyed functions, making them susceptible to modification by any attacker.   ",
    "A Message Authentication Code (MAC) is created using a secret symmetric key.   ",
    "A digital signature involves encrypting the message digest with the public key of an asymmetric key pair.",
    "In the scenario where Alice and Bob communicate over an insecure channel, if David can modify the hash, hashes don’t provide integrity.",
    "SHA-256 (256-bit version of SHA-2) is vulnerable to length extension attacks.",
    "Hash functions process input data one block at a time.",
    "The bit-by-bit exclusive-OR (XOR) hash function produces a simple parity for each bit position.",
    "The effectiveness of the XOR-based hash function for random data is 2-n. ",
    "Performing a 1-bit circular shift on the hash value after each block is processed improves the function's effectiveness. ",
    "The second procedure, involving a 1-bit circular shift, is useful for data security when an encrypted hash code is used with a plaintext message.",
    "A simple XOR or rotated XOR (RXOR) is sufficient if only the hash code is encrypted.   ",
    "The National Bureau of Standards proposed using simple XOR applied to 64-bit blocks and encryption in CBC mode to enhance data security.",
    "The hash code remains unchanged if the ciphertext blocks are permuted in the proposed scheme. ",
    "The proposed scheme with XOR and CBC encryption ensures that the hash code is detectable in the ciphertext. ",
    "In the proposed scheme, XN+1 is the hash code defined as the block-by-block XOR of all blocks.",
    "A digital signature provides authentication of the sender's identity. ",
    "Digital signatures ensure the secrecy of the message being transmitted.",
    "Digital signatures use symmetric encryption for verification. ",
    " Digital signatures rely on a public key infrastructure (PKI). ",
    "Digital signatures can only be verified using the sender's public key. ",
    "Anyone can create a valid digital signature for a message without the private key. ",
    "Digital signatures are tamper-evident, meaning any changes to the message can be detected.",
    "Digital signatures are primarily used for encrypting data. ",
    " Digital signatures provide non-repudiation, meaning the sender cannot deny sending the message. ",
    " Digital signatures are vulnerable to interception during transmission. Lecture slide: 21, page: 3",
    "The Digital Signature Algorithm (DSA) is not one of the specified algorithms in FIPS 186-4. ",
    "In the digital signature generation process, Bob uses a public key to create a short block functioning as a digital signature. ",
    "The RSA Digital Signature Algorithm ensures confidentiality of the message being sent. ",
    "RSA-PSS introduces a pseudorandom salt that remains constant with every use. ",
    "Digital signatures provide protection against eavesdropping. "

]

true_false_correct_answers = [False, True, False, True, True, False, False, False, False, True, False, True, False,
                              False, False, True, False, True,
                              True,
                              False,
                              False,
                              True,
                              True,
                              True,
                              False,
                              True,
                              True,
                              True,
                              True,
                              False,
                              True,
                              False,
                              False,
                              True,
                              True,
                              False,
                              True, True, False, False, True, True, False, True, False, True, False, False, False,
                              False, False, False, ]

true_false_sources = ["Lecture Slide: 15 Page:3",
                      "Lecture Slide: 15 Page:3",
                      "Lecture Slide: 15 Page:3",
                      "Lecture Slide: 15 Page:4",
                      "Lecture Slide: 15 Page:4",
                      "Lecture Slide: 15 Page:5",
                      "Lecture Slide: 15 Page:6",
                      "Lecture Slide: 15 Page:6",
                      "Lecture Slide: 15 Page:7",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:91",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:91",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:93",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:92",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:92",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:91",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:91",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings Page:91",
                      "Lecture Slide: 16, Page: 5",
                      " Lecture Slide: 16, Page: 6",
                      "Lecture Slide: 16, Page: 7",
                      "Lecture Slide: 16, Page: 7",
                      "Lecture Slide: 16, Page: 6",
                      "Lecture Slide: 16, Page: 5",
                      "Lecture Slide: 17, Page: 7",
                      "Lecture Slide: 17, Page: 7",
                      "Lecture Slide: 17, Page: 5",
                      "Lecture Slide: 16, Page: 8",
                      " Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 87",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 89",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 87",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 89",
                      " Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 89",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 88",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 87",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 89",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 87",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 88",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      " Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      "Lecture slide:20, page : 7",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 148",
                      "Lecture slide: 20, Page: 7", "Lecture slide: 20, page: 7",
                      " Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
                      "Lecture slide: 21, page: 3",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
                      ]

# Open Ended Questions:
open_ended_questions = [
    "What is the main concern of message authentication? ",
    "Does symmetric message encryption, by itself, provide a measure of authentication? ",
    "If public-key encryption is used, what does encryption alone provide confidence in? ",
    "What is the solution mentioned to have both secrecy and authentication when using public-key encryption? Source: "
    "Lecture Slide: 15, Page:4",
    "Is encryption software generally fast or slow? ",
    "Are encryption hardware costs negligible or nonnegligible? ",
    "What is encryption hardware optimized toward? ",
    "May an encryption algorithm be protected by a patent? ",
    "What is the primary motivation for developing a MAC derived from a cryptographic hash code? ",
    "What is the primary disadvantage of using a hash function like SHA-1 directly for MAC purposes? ",
    "What is the acronym for the approach that incorporates a secret key into an existing hash algorithm? ",
    "Which RFC number specifies the design objectives for HMAC? ",
    "What is the main advantage of HMAC over other proposed hash-based schemes? ",
    "What does HMAC treat the hash function as? ",
    "What is the main benefit of treating the hash function as a 'black box' in HMAC implementation? ",
    "What can be easily replaced in an HMAC implementation if a faster hash function is desired? ",
    "What is the current standard for hash functions, not meant to replace SHA-2? ",
    "Name a widely used hash function known to be completely broken.",
    "What type of attack involves an attacker creating H(x || m) given H(x) and the length of x?",
    "In the scenario where Alice and Bob communicate over an insecure channel, what is the main issue if the attacker can modify the hash?",
    "What cryptographic technique can provide assurance that a message has not been modified using a secret symmetric key? ",
    "What is the cryptographic term for a fixed-size numeric representation of the contents of a message, computed by a hash function?   ",
    "What security property involves the infeasibility of finding any pair of inputs x' ≠ x such that H(x) = H(x')? ",
    "In the context of cryptographic hashes, what does the term 'random oracle' assumption refer to? ",
    "Which hash function output size is labeled SHA-256? ",
    "What is the main purpose of hashing the program binary and publishing the hash on the website in the scenario of downloading a program from a server?  ",
    "What cryptographic property ensures that an attacker cannot create a malicious program with the same hash as a legitimate program?   ",
    "What type of check is produced by the bit-by-bit XOR of every block?   ",
    "What is performed on the hash value after each block to improve the hash function? ",
    "What is the term for the encryption mode that involves the XOR of 64-bit blocks and the entire message encryption?   ",
    "What is the value initially set to the n-bit hash value?   ",
    "What is the term for the bit produced by the XOR operation of each bit position?   ",
    "What is the abbreviation for Cipher Block Chaining mode? ",
    "What is the term for overcoming regularities in the input by 'randomizing' it more completely? ",
    "What technique did the National Bureau of Standards propose involving the XOR of 64-bit blocks and CBC encryption? ",
    "An algorithm for transforming plaintext to ciphertext is called? ",
    " What is the process of converting plaintext to ciphertext? ",
    "What is the study of encryption principles/methods? ",
    "What is the study of principles/ methods of deciphering ciphertext without knowing key ",
    "Recovering plaintext from ciphertext is called? ",
    " The essence of the RSA digital signature algorithm is to encrypt?",
    " Generate hash value H from? ",
    " Asymmetric cryptography is good because we don’t need to share what key? ",
    "Primary purpose of a digital signature? ",
    "NIST-approved digital signature algorithms? ",
    "Bob uses a secure hash function for? ",
    "Alice verifies with Bob's? ",
    "RSA-PSS purpose? ",
    "Key elements in digital signature process? ",
    "RSA algorithm modifies hash for? ",
    "Salt's role in RSA-PSS? ",
    "Non-repudiation means?",
    "Why no confidentiality in encryption? "
]

open_ended_correct_answers = [
    "Integrity", "Yes", "Confidenceofsender", "Signs", "Slow", "Nonnegligible", "Large data sizes", "Yes", "Speed",
    "NoSecretKey", "HMAC", "RFC2104", "Security", "BlackBox", "Module", "HashFunction", "SHA-3",
    "MD5",
    "Lengthextension",
    "Integrity",
    " MAC",
    "Messagedigest",
    "Strongcollisionresistance",
    "Random/unpredictability",
    "256",
    "Tamperdetection",
    "Collisionresistance",
    "Longitudinal",
    "Rotation",
    "CBC",
    "Zero",
    "Parity",
    "CBC",
    "Randomizing",
    "RXOR",
    "cipher",
    "encrypt",
    "cryptography ",
    "cryptanalysis ",
    "decrypt",
    "hash",
    " secretkey",
    "Authentication",
    "RSA",
    "Hash",
    "Public",
    "Security",
    "Hash",
    "Security",
    "Security",
    "Denial",
    "Clear"
]

open_ended_sources = ["Lecture Slide: 15, Page:3", "Lecture Slide: 15, Page:3", "Lecture Slide: 15, Page:3",
                      "Lecture Slide: 15, Page:5", "Lecture Slide: 15, Page:5", "Lecture Slide: 15, Page:5",
                      "Lecture Slide: 15, Page:5",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page:91",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page:91",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page:92",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page:93",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page:91",
                      " Network Security Essentials Applications and Standards Sixth edition William Stallings, Page:92",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page:93",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page:93",
                      "Lecture Slide: 16, Page: 8", "Lecture Slide: 16, Page: 8", "Lecture Slide: 16, Page: 5",
                      " Lecture Slide: 17, Page: 5", "Lecture Slide: 17, Page: 7", "Lecture Slide: 16 , Page:7",
                      "Lecture Slide: 16, Page: 4", "Lecture Slide: 16, Page: 7", "Lecture Slide: 16, Page: 7",
                      "Lecture Slide: 17, Page: 5",
                      "Lecture Slide: 17, Page: 7",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 89",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 87",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 88",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 89",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 88",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 89",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 87",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page No: 87",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      " Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:112",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:203",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      " Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      "Lecture slide:20 , page 7",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      " Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no:111",
                      ]
