# MCQ questions with source information, choices, and correct answers
mcq_questions = ["What is user impersonation in the context of computer security?",
                 "What does network address impersonation involve?",
                 "What is the purpose of eavesdropping in unauthorized access?",
                 "In the context of computer security, what does tampering refer to?",
                 "What is the potential risk of replay attacks in computer security?",
                 "Which characteristic ensures that users shouldn't notice authentication taking place?",
                 "In terms of scalability, what does the system need to handle?",
                 "What is the protocol used for mutual authentication between users and servers in a centralized authentication server?",
                 "Where was the key distribution and user authentication service developed?",
                 "In which environment does the Kerberos protocol operate?",
                 "What is the model used in the client-service interaction of Kerberos?",
                 "What is the TGS?",
                 "How does the client authenticate itself to the TGS?",
                 "What is included in the ticket-granting ticket (Tickettgs)?",
                 "What prevents alteration of the ticket-granting ticket?",
                 "How is the ticket-granting ticket encrypted initially?",
                 "What does the client need for recovery of the ticket?",
                 "What is the purpose of re-encrypting the ticket with a user's password?",
                 "What is the structure of a service-granting ticket?",
                 "Why is there a need for servers to authenticate themselves to users?",
                 "What threat arises with captured ticket-granting tickets?",
                 "How does the client prove its identity to the TGS?",
                 "What is the secure piece of information used for identity verification in Kerberos?",
                 "What is the session key in Kerberos?",
                 "What is the main challenge in key distribution for end-to-end encryption over a network?  ",
                 "In option 4 of key distribution, what are the two kinds of keys used?  ",
                 "What is the role of a Key Distribution Center (KDC) in the key distribution process?  ",
                 "Which key is used to encrypt the communication between a host and the KDC during a connection request in option 4?  ",
                 "What does the KDC deliver to hosts A and B after approving a connection request?  ",
                 "Why is manual key delivery impractical for end-to-end encryption in a distributed system?  ",
                 "What is the term used for the key distribution approach involving a Key Distribution Center (KDC)? ",
                 "In the key distribution process, what does the KDC determine when host A wishes to set up a connection with host B?  ",
                 "What must two parties share for symmetric encryption to work?  ",
                 "What does the text suggest is a drawback of option 1 for key distribution?  "
                 ]

mcq_choices = [["Changing computer hardware", "Pretending to be another user", "Installing new software",
                "Enhancing network speed"],
               ["Changing computer passwords", "Modifying system files",
                "Altering the network address to impersonate another workstation", "Upgrading network protocols"],
               ["Enhancing network security", "Monitoring and recording conversations", "Deleting sensitive data",
                "Improving system performance"],
               ["Improving system efficiency", "Unauthorized modification of data", "Routine system maintenance",
                "Increasing network speed"],
               ["Slowing down network communication", "Repeating or reusing captured data to gain unauthorized access",
                "Enhancing encryption algorithms", "Increasing system storage capacity"],
               ["Transparency", "Scalability", "Entering passwords frequently", "Malicious attacks"],
               ["Large number of users and servers", "Minimal security features", "Low scalability",
                "Limited user interaction"],
               ["OAuth", "Kerberos", "LDAP", "SAML"],
               ["Harvard", "MIT", "Stanford", "Caltech"],
               ["Closed", "Isolated", "Centralized", "Open Distributed"],
               ["Peer-to-peer", "Client-server", "Mesh", "Star"],
               ["Ticket-Granting System", "Ticket-Generating Service", "Token-Granting Server",
                "Time-Generating Service"],
               ["By sending a plaintext password", "By using a public key", "By presenting the Tickettgs",
                "By sending a request to the AS"],
               ["User ID and network address", "TGS ID and password", "Service ID and user's password",
                "User ID, network address, and TGS ID"],
               ["Timestamp", "Secret Key (Kv)", "Secret Key (Ktgs)", "Lifetime"],
               ["Secret Key (Kv)", "Secret Key (Ktgs)", "User's Password", "Timestamp"],
               ["Secret Key (Kv)", "Secret Key (Ktgs)", "User's Password", "Lifetime"],
               ["Lifetime", "Secret Key (Kv)", "Secret Key (Ktgs)", "Timestamp"],
               ["Timestamp and Lifetime", "User's ID and Network Address", "Service ID",
                "Ticket-Granting Ticket Structure"],
               ["PreventReplayAttacks", "PreventConfigurationSabotage", "EnsureAvailability", "EnhanceEncryption"],
               ["DenialOfService", "UnauthorizedAccess", "IdentityTheft", "SessionExpiry"],
               ["By presenting the ticket", "By revealing a secret piece of information", "By using a public key",
                "By sending a plaintext message"],
               ["Timestamp", "Session Key", "Ticket-Granting Ticket", "Server ID"],
               ["UniqueIdentifier", "SecretPiece", "AuthenticationKey", "TemporaryKey"],
               ["Manual delivery of keys", "Session key destruction", "Key encryption by a third party",
                "Permanent key sharing"],
               ["Public key and private key", "Master key and session key", "Temporary key and permanent key",
                "Session key and permanent key"],
               ["Encrypting user data", "Approving logical connections", "Generating permanent keys",
                "Destroying session keys"],
               ["Permanent key", "Session key", "Master key", "Temporary key"],
               ["Public key", "Master key", "Session key", "Temporary key"],
               ["It is highly secure", "It is scalable", "It is time-efficient", "It is not scalable"],
               ["Public-key cryptography", "Hybrid encryption", "Automated key distribution", "Manual key exchange"],
               ["Encryption algorithm", "Session key", "Communication permission", "Public key"],
               ["Public key", "Private key", "Session key", "Symmetric key"],
               ["It is insecure.", "It requires manual delivery.", "It involves too many keys.", "It is not scalable."]]

mcq_correct_answers = ["Pretending to be another user",
                       "Altering the network address to impersonate another workstation",
                       "Monitoring and recording conversations",
                       "Unauthorized modification of data",
                       "Repeating or reusing captured data to gain unauthorized access",
                       "Transparency",
                       "Large number of users and servers",
                       "Kerberos",
                       "MIT",
                       "Open Distributed",
                       "Client-server",
                       "Ticket-Generating Service",
                       "By presenting the Tickettgs",
                       "User ID, network address, and TGS ID",
                       "Secret Key (Ktgs)",
                       "Secret Key (Kv)",
                       "User's Password",
                       "PreventReplayAttacks",
                       "Timestamp and Lifetime",
                       "PreventConfigurationSabotage",
                       "IdentityTheft",
                       "By revealing a secret piece of information",
                       "Session Key",
                       "TemporaryKey",
                       "Manual delivery of keys",
                       "Session key and permanent key",
                       "Approving logical connections",
                       "Master key",
                       "Session key",
                       "It is not scalable",
                       "Automated key distribution",
                       "Communication permission",
                       "Symmetric key",
                       "It requires manual delivery"
                       ]

mcq_sources = ["lecture slide_22, page no: 9",
               "lecture slide_22, page no: 9",
               "lecture slide_22, page no: 9",
               "lecture slide_22, page no: 9",
               "lecture slide_22, page no: 9",
               "lecture slide_22, page no: 10",
               "lecture slide_22, page no: 10",
               "lecture slide_22, page no: 12",
               "lecture slide_22 page no: 12",
               "lecture slide_22, page no: 12",
               "lecture slide_22, page no: 12",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 127",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 127",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 127",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 128",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 128",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 128",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 128",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 128",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
               ]

# True/False questions and correct answers
true_false_questions = [
    "Malicious user with access to a workstation pretends to be another user from the same workstation. ",
    "Malicious user changes network address of his workstation to impersonate another workstation. ",
    "Malicious user eavesdrops, tampers, or replays other users’ conversations to gain unauthorized access. ",
    "Security measures are in place against attacks by eavesdroppers and malicious users.",
    "Transparency means users should actively notice the authentication process.",
    "Scalability refers to handling a limited number of users and servers. ",
    "Kerberos protocol messages are susceptible to eavesdropping. ",
    "Kerberos v5 is specified in RFC 4120. ",
    "The ticket-granting ticket (Tickettgs) is reusable. ",
    "The ticket-granting ticket includes a timestamp and a lifetime. ",
    "The TGS uses a key shared only with the AS for decrypting the ticket.",
    "The service-granting ticket has a different structure than the ticket-granting ticket. ",
    "The second problem discussed is related to the potential for servers to authenticate themselves to users.",
    "Captured ticket-granting tickets pose a threat because an opponent may use them before they expire. ",
    "In Kerberos, the client proves its identity to the TGS by presenting the ticket.",
    "The session key in Kerberos is included in the ticket-granting ticket and can be read by both the client and the TGS.",
    "The first phase of the Kerberos dialogue includes a timestamp in the message to ensure its timeliness.",
    "Symmetric key distribution uses the same key for both encryption and decryption.  ",
    "Symmetric key distribution is more efficient than asymmetric key distribution. ",
    "The primary challenge in symmetric key distribution is securely exchanging the initial key.  ",
    "Symmetric key distribution is suitable for large-scale encryption without added complexity.  ",
    "Interception of the symmetric key can compromise the security of the communication  ",
    "AES is an example of a symmetric encryption algorithm used in key distribution. ",
    "Symmetric key distribution requires a public and private key pair.  ",
    "Key management is less important in symmetric key distribution compared to asymmetric key distribution.  ",
    "Symmetric key distribution is generally faster than asymmetric key distribution for encryption and decryption.  ",
    "Symmetric encryption requires frequent key changes to limit data exposure in case of a compromised key.  ",
    "Permanent keys are used for encrypting user data during a session between two hosts.  ",
    " A session key, used for the duration of a logical connection, is reused for subsequent connections between the same hosts.  ",
    "Automated key distribution, as described in the text, is primarily suitable for link encryption but not for end-to-end encryption in a network.  "

]

true_false_correct_answers = [True, True, True, True, False, False, False, True, True, True, True, False, True, True,
                              False, False, True, True, True, True, False, True, True, False, False, True, True, False,
                              False, False]

true_false_sources = ["lecture slide_22, page no: 9",
                      "lecture slide_22, page no: 9",
                      "lecture slide_22, page no: 9",
                      "lecture slide_22, page no: 10",
                      "lecture slide_22, page no: 10",
                      "lecture slide_22, page no: 10",
                      "lecture slide_22, page no: 12",
                      "lecture slide_22, page no: 12",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 127",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 127",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 128",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 128",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
                      "Leacture slide:22, page: 5",
                      "Leacture slide:22, page: 5",
                      "Leacture slide:22, page: 5",
                      "Leacture slide:22, page: 5",
                      "Leacture slide:22, page: 5",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
                      "Leacture slide:22, page: 5",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 123"

                      ]

# Open-ended questions and correct answers
open_ended_questions = [
    "What is the term for a malicious user pretending to be another user from the same workstation? ",
    "What is the term for a malicious user changing the network address of their workstation to impersonate another workstation? ",
    "What term describes a malicious user eavesdropping, tampering, or replaying other user's conversations to gain unauthorized access? ",
    "What is the primary security concern against eavesdroppers and malicious users? ",
    "What characteristic ensures that users shouldn't actively notice authentication taking place? ",
    "When is entering a password considered acceptable? ",
    "Name the versions of the Kerberos protocol specified in RFC 4120. ",
    "Any one type of attack Kerberos protocol messages protected against? ",
    "What is the TGS? ",
    "Why is a timestamp included in the ticket? ",
    "What is the lifetime of the ticket?   ",
    "What is the purpose of re-encrypting the ticket with a user's password? ",
    "What additional requirement is introduced to address security concerns? ",
    "What issue does the system face with the lifetime of the ticket-granting ticket? ",
    "What is the purpose of distributing a session key? ",
    "How does Kerberos address the threat of stolen ticket-granting tickets?",
    "What is Symmetric Key Distribution?  ",
    "Why use Symmetric Key Distribution? ",
    "How to securely share keys? Source: ",
    "What's a common symmetric algorithm? ",
    "Is key management crucial?",
    "What is Symmetric key vulnerabilities? ",
    "Strength of symmetric encryption is known for? Source:  ",
    "What is the primary goal of key distribution in symmetric encryption? ",
    "Why is manual key delivery impractical for end-to-end encryption in a distributed system? ",
    "What does a session key represent in the context of end-to-end encryption? ",
    "What type of connection does a session key secure between two hosts during communication? ",
    "Why is destroying session keys after a logical connection concludes considered a security measure? ",
    "In symmetric encryption, what must two parties share for secure communication to occur? "

]

open_ended_correct_answers = ["Impersonation",
                              "NetworkAddressImpersonation",
                              "Eavesdropping",
                              "Security",
                              "Transparency",
                              "Rarely",
                              "Kerberosv4andv5",
                              "Eavesdropping attacks",
                              "Ticket-Granting Service",
                              "PreventReplayAttacks",
                              "EightHours",
                              "Authentication",
                              "ProvingIdentity",
                              "ReplayAttacks",
                              "IdentityVerification",
                              "UsingEncryptionKey",
                              "Encryption",
                              "Efficiency",
                              "Key exchange",
                              "AES",
                              "Yes",
                              "Interception",
                              "Speed",
                              "Security",
                              "Scalability",
                              "Temporary",
                              "Logical",
                              "Mitigation",
                              "Key"]

open_ended_sources = ["lecture slide_22, page no: 9",
                              "lecture slide_22, page no: 9",
                              "lecture slide_22, page no: 9",
                              "lecture slide_22, page no: 10",
                              "lecture slide_22, page no: 10",
                              "lecture slide_22, page no: 10",
                              "lecture slide_22, page no: 12",
                              "lecture slide_22, page no: 12",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 127",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 127",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 127",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 128",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 128",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 128",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 129",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 123",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 123",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 139",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 270",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 123",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 123",
                              "Leacture slide:22, page: 6",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 123",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 123",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 123",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 123",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 123",
                              "Network Security Essentials Applications and Standards Sixth edition William Stallings, page no: 123"
                              ]
