# MCQs related to stream cipher encryption and random numbers
mcq_questions = [
    "What is a characteristic feature of processing messages in a stream cipher? ",
    "What operation is typically used to combine the stream key with the plaintext bit by bit? ",
    "Why is the randomness of the stream key important in stream ciphers?. ",
    "What is the mathematical representation of the encryption process in a stream cipher?. ",
    "Why is it crucial to never reuse the stream key in a stream cipher?.",
    "What happens if the stream key is reused in a stream cipher according to the provided information?.",
    "What is the simplicity of the XOR operation in stream ciphers attributed to?.",
    "What does a large period of repeat in the encryption sequence of a pseudorandom number generator make cryptanalysis?.",
    "Why is it important for the keystream in a stream cipher to approximate the properties of a true random number stream?. ",
    "In stream ciphers, how is the output of the pseudorandom number generator conditioned?.",
    "To guard against brute-force attacks, what is the recommended key length for a stream cipher?.",
    "How does the security of a properly designed pseudorandom number generator compare to a block cipher of comparable key length in a stream cipher?. ",
    "What is a potential advantage of stream ciphers over block ciphers?.",
    "What factor has diminished the historical advantage of stream ciphers over block ciphers in recent years?.",
    "How does hardware acceleration, such as the Intel AES Instruction Set, impact the efficiency of AES compared to pure software implementations?.",
    "Which type of numbers is generated in a non-deterministic way?",
    "How are pseudorandom numbers obtained?",
    "Can true random numbers be predicted and repeated?",
    "What is a key property of random numbers related to their even distribution?",
    "Which property ensures that no subsequence can be inferred from others?",
    "What does the 'next-bit test' assess in random numbers?"
]

mcq_choices = [
    ["Block processing", "Bit processing", "Character processing", "String processing"],
    ["Addition", "Multiplication", "XOR", "Subtraction"],
    ["To speed up encryption", "To create patterns in ciphertext", "To destroy statistical properties",
     "To simplify the algorithm"],
    ["Ci = Mi + StreamKeyi", "Ci = Mi * StreamKeyi", "Ci = Mi / StreamKeyi", "Ci = Mi XOR StreamKeyi"],
    ["It enhances security", "It simplifies the encryption process", "It speeds up the decryption process",
     "It prevents the recovery of messages"],
    ["It strengthens the encryption", "It makes the ciphertext longer",
     "It weakens the security, allowing message recovery", "It simplifies the decryption process"],
    ["Faster key generation", "Simplified ciphertext structure", "Efficiency and simplicity of the encryption process",
     "Increased vulnerability to attacks"],
    ["Makes cryptanalysis easier", "Increases the difficulty of cryptanalysis", "Does not impact cryptanalysis",
     "Reduces the key length"],
    ["To simplify encryption", "To make decryption faster", "To increase the randomness of the ciphertext",
     "To reduce the key length"],
    ["On the plaintext", "On the ciphertext", "On the value of the input key", "On the key length"],
    ["At least 64 bits", "At least 128 bits", "Exactly 256 bits", "No specific key length requirement"],
    ["It is more secure", "It is less secure", "It is equally secure", "It depends on the specific algorithm"],
    ["Faster implementation", "Smaller key size", "More complex code", "Greater resistance to brute-force attacks"],
    ["Introduction of RC4", "Introduction of AES", "Introduction of hardware acceleration",
     "Introduction of stream ciphers"],
    ["Reduces efficiency", "Has no impact", "Results in slower encryption",
     "Results in speedups of about an order of magnitude"],
    ["Pseudorandom numbers", "Deterministic numbers", "Random and predictable numbers", "None of the above"],
    ["Through random events", "In a deterministic way", "By guessing", "Using algorithms"],
    ["Yes", "No", "Sometimes", "Depends on the source"],
    ["Randomness", "Uniformity", "Independence", "Unpredictability"],
    ["Randomness", "Uniformity", "Independence", "Unpredictability"],
    ["Distribution", "Uniformity", "Independence", "Predictability"]
]

mcq_correct_answers = [
    "Bit processing",
    "XOR",
    "To destroy statistical properties",
    "Ci = Mi XOR StreamKeyi",
    "It prevents the recovery of messages",
    "It weakens the security, allowing message recovery",
    "Efficiency and simplicity of the encryption process",
    "Increases the difficulty of cryptanalysis",
    "To increase the randomness of the ciphertext",
    "On the value of the input key",
    "At least 128 bits",
    "It is equally secure",
    "Faster implementation",
    "Introduction of AES",
    "Results in speedups of about an order of magnitude",
    "Pseudorandom numbers",
    "Using algorithms",
    "No",
    "Uniformity",
    "Independence",
    "Unpredictability"
]

mcq_sources = ["Lecture slide:10, page: 3",
               "Lecture slide:10, page: 3",
               "Lecture slide:10, page: 3",
               "Lecture slide:10, page: 3",
               "Lecture slide:10, page: 3",
               "Lecture slide:10, page: 3",
               "Lecture slide:10, page: 3",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
               "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
               "Lecture Slide: 8 Page:4",
               "Lecture Slide: 8 Page:4",
               "Lecture Slide: 8 Page:4 ",
               "Lecture Slide: 8 Page:5 ",
               "Lecture Slide: 8 Page:5",
               "Lecture Slide: 8 Page:5"
               ]

# True/False questions and correct answers
true_false_questions = [
    "A stream cipher processes the message block by block.",
    "The randomness of the stream key enhances the statistical properties of the message.",
    "In stream ciphers, the encryption operation is typically XOR between the plaintext and stream key.",
    "Reusing the stream key in a stream cipher does not affect the security of the encryption.",
    "The longer the period of repeat in a pseudorandom number generator, the easier it is to perform cryptanalysis.",
    "The key length in a stream cipher should be at least 256 bits to guard against brute-force attacks.",
    "A stream cipher with a properly designed pseudorandom number generator can be as secure as a block cipher with a comparable key length.",
    "The advantage of stream ciphers over block ciphers in terms of code size has increased in recent years.",
    "A large period of repeat in the encryption sequence makes cryptanalysis easier. ?.",
    "The keystream in a stream cipher should have an equal number of 1s and 0s for better security. ?.",
    " The output of a pseudorandom number generator in a stream cipher is conditioned on the value of the input key. ?.",
    "Reusing the stream key in a stream cipher does not affect the security of the encryption. ?.",
    "A key length of at least 128 bits is desirable to guard against brute-force attacks in stream ciphers. ?.",
    "Stream ciphers that do not use block ciphers as a building block are typically slower than block ciphers. ?.",
    "The advantage of stream ciphers over block ciphers in terms of code size has increased in recent years. ?.",
    "Hardware acceleration techniques, such as the Intel AES Instruction Set, result in speedups for AES compared to pure software implementations. ?.",
    "True random numbers are always predictable.",
    "Pseudorandom numbers are obtained through algorithms.",
    "Random numbers should have a uniform distribution of bits.",
    "If a subsequence can be inferred from another, it violates the property of Independence.",
    "'Next-bit test' assesses the distribution of bits in a sequence."]
true_false_correct_answers = [
    False,
    False,
    True,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    True,
    False,
    True,
    False,
    False,
    True,
    False,
    True,
    True,
    True,
    False
]
true_false_sources = ["Lecture slide:10, page: 3",
                      "Lecture slide:10, page: 3",
                      "Lecture slide:10, page: 3",
                      "Lecture slide:10, page: 3",
                      "Lecture slide:10, page: 3",
                      " Lecture slide:10, page: 3",
                      "Lecture slide:10, page: 3",
                      "Lecture slide:10, page: 3",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Lecture Slide: 8 Page:4",
                      "Lecture Slide: 8 Page:4",
                      "Lecture Slide: 8 Page:5",
                      "Lecture Slide: 8 Page:5",
                      "Lecture Slide: 8 Page:5"
                      ]

# Open-ended questions and correct answers
open_ended_questions = [
    "Name a key operation used in stream ciphers.",
    "What destroys statistical properties in the message in stream ciphers?",
    "In stream ciphers, what should the stream key be to enhance security?.",
    "What should you never do with the stream key in stream ciphers?.",
    "What happens if the stream key is reused in stream ciphers?.",
    "Name a desirable property for the period of a pseudorandom number generator in encryption.",
    "What should the keystream in a stream cipher approximate to enhance security?",
    "In stream ciphers, what is the key length recommended to guard against brute-force attacks?.",
    "What type of cipher can be as secure as a block cipher with a properly designed pseudorandom number generator?.",
    "What is a potential advantage of stream ciphers over block ciphers in terms of code size?.",
    "What is an example of a stream cipher that can be implemented in just a few lines of code?.",
    "What technology has diminished the historical advantage of stream ciphers in recent years?.",
    "What set of machine instructions provides hardware acceleration for AES?.",
    "Describe true randomness in one word.",
    "What is a limitation of pseudorandom numbers?",
    "Define the key property related to the even distribution of bits in random numbers.",
    "What is assessed by the 'next-bit test' in random numbers?"

]

open_ended_correct_answers = [
    "XOR",
    "Randomness",
    "Pseudorandom",
    "Reuse",
    "Recovery",
    "Large",
    "Randomness",
    "128",
    "Stream",
    "Faster",
    "RC4",
    "AES",
    "Intel",
    "Unpredictable",
    "Deterministic",
    "Uniformity",
    "Unpredictability"
]

open_ended_sources = ["Lecture slide:10, page: 3 ",
                      "Lecture slide:10, page: 3 ",
                      "Lecture slide:10, page: 3 ",
                      "Lecture slide:10, page: 3 ",
                      "Lecture slide:10, page: 3",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Network Security Essentials Applications and Standards Sixth edition William Stallings, Page no: 64",
                      "Lecture Slide: 8 Page:4",
                      "Lecture Slide: 8 Page:4",
                      "Lecture Slide: 8 Page:5",
                      "Lecture Slide: 8 Page:5"]
